// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AddEmployeeDrawer: typeof import('./components/AddEmployeeDrawer.vue')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDashboard: typeof import('~icons/carbon/dashboard')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonHelp: typeof import('~icons/carbon/help')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    EmployeeDrawer: typeof import('./components/EmployeeDrawer.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    Provider: typeof import('./components/Provider.vue')['default']
    README: typeof import('./components/README.md')['default']
    UserDetail: typeof import('./components/UserDetail.vue')['default']
    Viewer: typeof import('./components/Viewer.vue')['default']
  }
}

export { }
